---

- name: Install samba
  ansible.builtin.apt:
    name: samba
    state: latest

- name: Start samba service
  ansible.builtin.service:
    name: smbd
    state: started

- name: add theZoo user to samba
  become: yes
  ansible.builtin.shell:
    "(echo {{smbpass}}; echo {{smbpass}}) | smbpasswd -s -a theZoo"

- name: Create foder for share
  ansible.builtin.file:
    path: /usr/share/theZoo
    state: directory

- name: Copy config
  ansible.builtin.copy:
    src: smb-config.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify: restart smbd