---
- hosts: ansiblehost
  strategy: free
  connection: local
  tasks:
    - include_role:
        name: the-zoo

- hosts: windows
  strategy: free
  tasks:
    - include_role:
        name: win10
      when: "'win10' in group_names"