---
# disable if microsoft defender
- name: Disable defender
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
    name: DisableWinDefender
    data: 1
    type: dword
    state: present

- name: Allow guest access
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
    name: AllowsecureGuestAuth
    data: 1
    type: dword
    state: present

- name: Install python
  win_chocolatey:
    name: python
    state: present

- name: Install edr tool msi
  block:
    - name: Copy agent installer to machine
      win_copy:
        src: edrinstaller.msi
        dest: "C:\\Users\\{{ansible_user}}\\Downloads"

    - name: Install edr agent
      win_package:
        path: C:\\Users\\{{ansible_user}}\\Downloads\\edrinstaller.msi
        state: present
  tags: ["install_msi"]

- name: Install edr tool msi
  block:
    - name: Copy agent installer to machine
      win_copy:
        src: edrinstaller.exe
        dest: "C:\\Users\\{{ansible_user}}\\Downloads"

    - name: Install edr agent
      win_package:
        path: C:\\Users\\{{ansible_user}}\\Downloads\\edrinstaller.exe
        state: present
  tags: ["install_exe"]


- name: Add share for malware test
  ansible.windows.win_shell: |
    CMDKEY /add:debian /user:"theZoo" /pass:"{{ share_password }}"
    net use "Z:" "\\debian\Share"   /persistent:yes /SAVECRED
