---

#Join domain

- name: Configure DNS
  win_dns_client:
    adapter_names: Ethernet0
    ipv4_addresses:
      - 10.168.160.5
      - 8.8.8.8

- name: Join domain
  microsoft.ad.membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ ansible_user }}@{{ domain_name }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain
  register: domain_state

- name: install old firefox version
  win_chocolatey:
    name: firefox
    version: '41.0'
    state: present
    force: true

- name: install google chrome
  win_chocolatey:
    name: googlechrome
    version: '87.0.4280.66'
    state: present
    force: true
    ignore_checksums: true

- name: Reboot after joining domain
  win_reboot:
  when: domain_state.reboot_required